### ISSUE TITLE
add a "none" option for the top term

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#1082]
currently we don't give people the option to not set a top term (even if it's something lame like "uncategorized"). We should add a "none" option to the dropdown menu in the admin and account for this in the front end display of the top tag (by just not returning any of the markup).

needed for RNS-127

**Comment by benlk** [comment]
This is going to involve changes in:

- [ ] largo_post_social_links to support a 'none' option for the top term, else it will try to get the taxonomy of the empty term.
- [ ] largo_top_tag_display to include a 'none' option
- [ ] the validation function saved with `largo_register_meta_input( 'top_term', 'intval' );` that are called at https://github.com/INN/Largo/blob/f4ddf0b27b5fc34fb826e7ac22a9c393b4cbed1a/inc/metabox-api.php#L135: this needs to not be intval, because the term id cannot be `'0'` because if it's `'0'` or `0` or `''` or any other value that computes as false-y, then largo [deletes the saved option]: therefore this has to be a string.

**Comment by benlk** [comment]
Closing this because the none option is available as of #1090 and #1092 has been created.
