### ISSUE TITLE
"don't miss" menu label is not displayed

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#1083]
Even with the menu activated, populated and a label provided in the theme options, the label does not display (not visually hidden, the markup isn't even being output)

**Comment by benlk** [comment]
The label name set in inc/nav-menus.php in [largo_add_dont_miss_label](https://github.com/INN/Largo/blob/master/inc/nav-menus.php#L25-L29) is hooked on the `wp_nav_menu_dont-miss_items` hook, which works if and only if the menu assigned to that area has a name that slugifies to "dont-miss". 

If the user assigns a different menu, like "Recommended", then it doesn't output because the hook is different.

**Comment by benlk** [comment]
To get the correct nav slug to use in the `add_action`, look at the wp_get_nav_menu_object call here: https://core.trac.wordpress.org/browser/tags/4.4.1/src/wp-includes/nav-menu-template.php#L301

The location is `dont-miss`, but the menu may be different.
