### ISSUE TITLE
What does the "Can distribute" checkbox in the featured media modal do?

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1146]

**Comment by aschweigert** [comment]
it's a holdover from argo, but in theory it could be used by sites that use photos for which they have limited rights to distribute beyond their own website. So, for example, a site might use photos from a wire service like AP or Getty but not be able to include those in their RSS feed or other distribution channels. If consistently implemented, this checkbox would be the way to flag those photos in the system and exclude them from whatever form of distribution that was not allowed. There wouldn't really be a "standard" implementation of this so that's why it's mostly just a placeholder with no other functionality attached to it on the publishing/distribution end.
