### ISSUE TITLE
evenly spacing nav items / flexbox?

### ISSUE THREAD

**Issue by tylermachado** [INN/Largo#1608]
Working on the INN mothership site's menu angst. Settled on a flexbox-y solution to evenly space things even when their own lengths vary. Worth putting into the Largo core codebase? Something like this on the nav ul on big screens. (There is probably a good argument against this that I am blanking on in the moment.)

`    
width: 100%;
display: flex;
justify-content: space-evenly;
flex-wrap: wrap; 
`

**Comment by benlk** [comment]
If we implement a Flexbox solution, we're dropping support for IE10 and below (a miniscule precent of US browsers), and we'd need to be careful about the known issues in IE11 (2.5% of US browsers). https://caniuse.com/#feat=flexbox

I'd like to redesign Largo's nav for 0.7, because the sticky nav menus code is a mess, and Largo's existing navs don't handle desktop well with many menu items. https://github.com/INN/largo/pull/1544

**Comment by benlk** [comment]
Removing from 0.7 milestone; keeping as an open issue because it's referenced in #1638's nav rebuild issue.
