### ISSUE TITLE
Find & update documentation for sites who want to upgrade the theme themselves, and make sure it's posted in our support documentation. 

### ISSUE THREAD

**Issue by MirandaEcho** [INN/Largo#1713]

**Comment by benlk** [comment]
- [x] add `SUPPORT` file for https://help.github.com/en/articles/adding-support-resources-to-your-project that sends people to largo.inn.org for docs, largo.readthedocs.io for developer documentation, and support@inn.org if they have questions not covered by the above
- [x] add this update docs to largo.inn.org
    - it's probably in Helpscout somewhere
    - there's also probably a version in github user @benlk's gists, or in INN/largo/tree/0.5-dev/docs
- [x] reference those update docs in the release notes and release blog post
    - [x] add task to release notes issue to make sure that the update docs are included in those

**Comment by MirandaEcho** [comment]
Here's a start: https://labs.inn.org/2018/12/14/updating-to-largo-0-6-1/

**Comment by benlk** [comment]
as seen in https://github.com/benlk/test-rst-health-files/issues/new:

- GitHub does support using .rst in Community Health Files
- GitHub does support drawing Community Health Files from multiple different folders in a repo

Therefore:

- to prevent duplication of support resources within the repo, the `SUPPORT` file should be placed in `docs/` in a reStructuredText format so that it gets picked up by the `largo.readthedocs.io` build
