### ISSUE TITLE
docs framework

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#302]
let's try to get sphinx (http://docs.writethedocs.org/tools/sphinx/) up and running and create some examples of how it would be used.

**Comment by willhaynes** [comment]
Docs now exist for all but the automatically generated php block comment *.rst files. Since I'd like to have some more discussion about how we want to organize this function reference (which will influence how it's built out) I'm going to close this immediate ticket and we can open up anther to discuss that.
