### ISSUE TITLE
backwards compatibility for three column homepage layout

### ISSUE THREAD

**Issue by ithacaindy** [INN/Largo#315]
Will a new child theme be released using the new structure found in 'development'? (I can't find how to alter the bottom portion of the homepage.)

**Comment by aschweigert** [comment]
we may not need this for the release but we should try to address it soon after because it will affect a number of the sites we host (gijn.org, c-hit.org, etc.)

**Comment by rnagle** [comment]
I added the three column layout back as a home template option. Some parts had to shift around, since I created a homepage layout using the new rig, but the update process and options page will handle sites using the three column template with no problem. See f550e6bd8b4de06e04824678092172e77456b215.

Bonus: filled out a bunch more tests for the homepages rig!
