### ISSUE TITLE
update script should only run once

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#380]
This is probably an edge case but since we accidentally ran the update once before for all INN sites (whoops), the main navigation menu area already exists for these sites. That sucks because when the update script is run again all of the items in that menu become duplicated because it tries to recombine the two other menu areas (categories and supplemental) into this one again.

So, we might want to keep track of whether the update script has run for each new version and NOT allow it to run again if, say, a site updates to 0.4, reverts to 0.3 (for whatever reason) and then updates again to 0.4.

**Comment by aschweigert** [comment]
This actually runs even when I set up a brand new site so we must just have a problem with comparing the version number or something, maybe?

**Comment by benlk** [comment]
It will run when brand-new sites are set up because `of_get_option('largo_version')` isn't set yet: see [largo_need_updates](https://github.com/INN/Largo/blob/master/inc/update.php#L20-L32).

Running the script sets some defaults that would otherwise have to be set manually, so I'm not sure why we wouldn't want to run it on new sites? The wording in [largo_update_admin_notice](https://github.com/INN/Largo/blob/master/inc/update.php#L458) might need tweaking, though, from "Largo has been updated" to something applicable to both updates and new installs, such as "You're using a new version of Largo".

`largo_version` isn't set or mentioned in tagged release `v0.3`, so there's no way to use the version number to be sure that an existing 0.3 site hasn't been updated to 0.4 and reverted to 0.3 at some point in the past. Those sites would read nothing or `0.4`.

To better check if the update was previously run, we could check for existence of the options framework options [that were added in 0.4 and in 0.4.1](https://gist.github.com/benlk/305bb7ef90fe535bd4cf):

- show_sticky_nav
- show_sitename_in_sticky_nav
- github_link
- single_social_icons
- post_types_enabled
- landing_left_region_default
- landing_right_region_default
- disclaimer_enabled
- default_disclaimer
- noindex_archives

And 0.4.1 should definitely bump `largo_version` to 0.4.1, for our sanity.

**Comment by aschweigert** [comment]
Yeah, running it for new sites is not a huge deal (as far as i can tell) although I feel like some defaults might not be being set correctly...things like the single article template, show name in sticky nav, etc. so we should verify that those work as expected. If they do, just tweaking the language or not showing the alert message for sites that don't need the update would be the best way to go here, I think.

**Comment by rnagle** [comment]
I have a couple thoughts on this. Let me know what you all think.

- The theme should not rely on anything in the update function to set default options. All defaults should be properly set in `options.php`.
- If we're trying to avoid duplication of menus for this edge case, maybe that part of the update should only run if the menus locations don't exist at the time the update check runs.
- The update function should put the theme in a predictable state no matter how many times it is run. It should ALWAYS render the same result no matter the configuration of the theme beforehand.
- Lastly, I personally feel like we could safely backlog this issue since it seems like it's only a problem for us because the update process previously ran automatically upon installing the newer version of the theme. It might be easy enough for us to address this by hand as we update sites in our network.

**Comment by aschweigert** [comment]
Yeah, i'd agree with all of that. Discounting the edge case described in the original ticket, I think the main thing here is the repeatability thing (which I think you capture pretty well) and then some things around the message(s) users receive during the update process, particularly on new installs it seems weird to ask users to "update" when they just installed WP/Largo because it wouldn't be clear to them what they're updating or why.

**Comment by rnagle** [comment]
Created #690 to address the issue of the update nag showing upon first install/activation. Going to backlog this ticket since the edge case seems extremely edge case-y to me at this point.
