### ISSUE TITLE
Series Posts Widget styles don't match other widgets

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#384]
Looks like the font is hard coded, headline size is different, a number of other oddities
![series-posts-widget](https://cloud.githubusercontent.com/assets/490703/5961300/b2e7052e-a7a9-11e4-81ea-c1c2ec0bec93.png)

**Comment by benlk** [comment]
![screenshot - 02102015 - 04 01 06 pm](https://cloud.githubusercontent.com/assets/1754187/6136368/24fd7498-b13e-11e4-946f-0195b561a4ba.png)

`a.more` no longer bold, to match the INN Member Stories widget's non-bold serif. The Largo Explore Related widget uses bold sans for this, though.
`ul a` no longer has margin-left, because it looked odd
`ul a` now uses sans font family, to match other headlines
`h5`, `h5 a` colors now `@black` to match other widget headlines

79d29d000bbcb67f0a65c787291db431529d5172

**Comment by benlk** [comment]
PR merged, so closing.
