### ISSUE TITLE
Support filtering river review by prominence (or other taxonomies) in addition to categories

### ISSUE THREAD

**Issue by ithacaindy** [INN/Largo#385]
Please consider increasing the options for selecting which posts to display/not display. Perhaps add a drop-down allowing users to filter posts by Post Prominence or Taxonomy. I'd like to filter main frontpage posts using the "Featured Frontpage" prominence taxonomy.

**Comment by aschweigert** [comment]
Hi Ed - That's a good suggestion, we'll probably tackle it in 0.6 (which is going to be focused on improving the admin experience), our release schedule is now going to be a release at the end of every quarter and the releases will be much smaller and more focused so that's the logical release for us to tackle improvements to that bit.

**Comment by aschweigert** [comment]
duplicates #167
