### ISSUE TITLE
featured media - what happens on the homepage when featured media is not an image?

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#391]
Right now, nothing. We need to figure out how this should work.

For galleries and videos this seems relatively straightforward, for the other embedded media I'm less sure...should it display? or should people be able to add a thumbnail image AND the embedded content? How would that workflow work out?

**Comment by tothebeat** [comment]
If the embedded media comes from a source that supports oEmbed, and the provider supplies the thumbnail, then that could be used for what appears on the home page. That's a big IF. The way different providers support oEmbed varies too. This project has a list of providers that support oEmbed in some form: https://noembed.com/

However, for generic embeds via embed code, such as the generic `<iframe>` embed where potentially anything could appear there, it would be technically challenging to generate a preview image. Not to mention the fact that the automatically generated preview image may not actually be what publishers want.

Even in the case of YouTube, one of the most well-behaved media providers with respect to WordPress, the preview image for a video may not be the most attractive or helpful image for that video. In many cases when I worked at Hoy, people wanted more editorial control over that preview image and provided their own frame grab of the video in addition to the video itself.

The workflow might be something like:

1. Writer chooses featured media.
2. Featured Media tool indicates whether there is a preview image available for the selected media and shows that image.
2a. If there is no preview image, suggest to the writer that they may want to add an image manually. Otherwise, indicate that there will be no preview image on the front page.
2b. If there is a preview image, suggest to the writer that they can override this by adding a featured image manually. Do not offer an option to show no featured media.

In the case of there being a preview image available with the featured media chosen, it seems unlikely to me that a writer would rather show nothing on the homepage as preview instead of the preview image or selecting another image manually.

**Comment by aschweigert** [comment]
see also: http://jira.inn.org/browse/HELPDESK-197

This is currently actually broken in the top-stories homepage layout, the video just doesn't display since we changed the way featured media is working. We probably need to account for this and add something to the update script for 0.3 -> 0.4 or otherwise somehow ensure backwards compatibility.

**Comment by aschweigert** [comment]
So, in the featured media modal on the post edit screen:

- [ ] if a user selects "slideshow" they need to be able to set which image should be used as the "cover" image for the slideshow and as the post thumbnail (we could also just use the first image, probably) (maybe overlay some sort of indication that it's a slideshow)
- [ ] if a user selects "video" we should try to pull a youtube thumbnail if available and use that as the post thumbnail (maybe overlay a "play" icon or something to indicate it's a video?)
- [ ] some users may want to NOT use the youtube thumbnail and we should allow them to set the post thumbnail manually
- [ ] for the generic embed option we need to allow people to ALSO upload/set a post thumbnail (and maybe overlay an icon or something to indicate the post has interactive content)

If we do all of the above, we should be able to just continue using the post thumbnail stuff as-is on the homepage/archive pages/etc. right?
