### ISSUE TITLE
dates on article pages

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#405]
On the new (single column) article pages there's no date displayed, there should be.

In the Wisconsin Watch child theme they're displayed at the very top right, see: http://wisconsinwatch.org/2015/02/ashley-furniture-fined-for-workplace-safety-violations-gets-state-tax-credits/

Let's make sure this makes it back into Largo as the default.

**Comment by benlk** [comment]
Wisconsin Watch does this by hooking `largo_before_post_header`: [source](https://bitbucket.org/projectlargo/wisconsinwatch/src/af2475332e856baad05a0a0a187454e4e6eb185c/functions.php?at=largo-0.4#cl-23). 

Should the fix for this replicate that as a pluggable function for backwards compatibility with Wisconsin Watch, or should the date code be added to [`partials/content-single.php`](https://github.com/INN/Largo/blob/master/partials/content-single.php#L9) in the same spot and the Wisconsin Watch theme updated to no longer use that function?

**Comment by benlk** [comment]
Resolved with f0a944ef4f8ee11f50acb5d5b0aeb9b785507b6f and styling in 9fbe6e348bacb742d742d2f252da92f3ca7c588c.
