### ISSUE TITLE
Homepage single w/ series layout doesn't show other stories featured in the series

### ISSUE THREAD

**Issue by rnagle** [INN/Largo#408]
There should be a list of stories to the right of the top story from the same series.

In this case, I tested with six posts in a series. All were set to "featured in series" via post prominence. Only the most recently published story shows on the homepage.

See screenshot:
![Homepage single w/ series not working](https://s3.amazonaws.com/uploads.hipchat.com/93536/778380/gQIs2mzBDIZ1EvB/Screen%20Shot%202015-02-17%20at%2010.42.42%20AM.png)

**Comment by benlk** [comment]
With: 
- a series of 5 posts
    - two Homepage Featured
    - none Featured in Series
- Homepage single with series layout chosen

It didn't show any series posts.

I added one post to Featured in Series. Three stories appeared, from a different series.

I removed that post from Featured in Series. The three stories from a different series remained visible. 

The HomepageSingleWithSeriesStories layout uses `homepage_series_stories_list` from `homepages/zones/zones.php`. `homepage_series_stories_list` grabs the series posts using 

	$feature = largo_get_the_main_feature();
	$series_posts = largo_get_recent_posts_for_term($feature, 3, 2);

$feature is a term from the series taxonomy of global $post at the time it was called. That post? The sticky post.

I think we've had problems with the sticky post messing with The Loop before.

**Comment by benlk** [comment]
So the issue here is that [largo_get_the_main_feature()](https://github.com/INN/Largo/blob/master/inc/featured-content.php#L40) is not Loop-agnostic, with no way to pass a post ID to it. There are two ways to solve the problem in this issue:

- replace ```$feature = largo_get_the_main_feature();``` in [homepage_series_stories_list](https://github.com/INN/Largo/blob/master/homepages/zones/zones.php#L54) with ```$featured = largo_home_single_top(); $feature = wp_get_post_terms( $featured->ID, 'series');```
- change `largo_get_the_main_feature();` to accept a post object as an argument (default would be global $post) and use that to get the term.

Which do you think would be better?

----

Unrelatedly: Is there a reason [why there isn't a wp_reset_postdata(); here](https://github.com/INN/Largo/blame/master/homepages/zones/zones.php#L70-L71)? It doesn't affect this problem, but it's used in the same place everywhere else.

**Comment by aschweigert** [comment]
I'd probably change the function to accept a post object.

Adding wp_reset_postdata there also seems like a good idea to me

**Comment by benlk** [comment]
![largo test site just another wordpress site](https://cloud.githubusercontent.com/assets/1754187/6669692/9db22210-cbd0-11e4-8347-aeba1d9a4095.png)

Do we want to keep the duplicate top term?

**Comment by aschweigert** [comment]
seems kind of weird, maybe the right column should say "more in TERM" or something instead. I think it helps to give some indication that the stories are related but duplicating the slug there doesn't really make sense. ping @kaeti

**Comment by kaeti** [comment]
"More in [term]" for the righthand column makes sense to me.

**Comment by benlk** [comment]
[That's added.](https://github.com/INN/Largo/commit/9ad6b721656e922ca542e36fa4575dafd6265be3)

**Comment by rnagle** [comment]
Fixed in fa2ee13ab05c852fd72d4ec9b35ecde60e95ac3f.
