### ISSUE TITLE
duplicate prominence terms in 0.4

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#414]
This is true, as far as I can tell for all sites that have updated from 0.3 to 0.4. 

Now that we made the prominence taxonomy "flat" instead of making "top story" a child of "homepage featured" there are duplicate terms that are confusing everyone, seeL

![duplicate-terms](https://cloud.githubusercontent.com/assets/490703/6334581/853968c4-bb63-11e4-92e3-2894a976e106.png)

This is particularly a problem because the homepage layouts are using either the slug or the term name to get the featured posts in various contexts. We need to go through this much more carefully and make sure that:

a) duplicate terms are not created (and delete/rename terms as necessary)
b) all homepage layouts are getting the featured posts THE SAME WAY (either by slug or term name) so future updates will be less fraught

**Comment by benlk** [comment]
Are there any sites that are *not* experiencing this? I think they'd be ones using:

- no homepage top option
- Blog
- Top Stories

If that's the case, then it's because we don't remove the previously-existing "Top Story" prominence and the slug is duplicated by the other layouts, which create a new prominence term when they're in use.
