### ISSUE TITLE
single hero homepage layout shows incorrect byline

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#415]
Reported by http://investigatemidwest.org/

The top story on their homepage is showing the byline for the most recent story on their site instead of the byline that belongs with the homepage top story. 

They're not using a child theme or anything so this is definitely an issue with that homepage layout that we need to look into and figure out what's going on.

**Comment by benlk** [comment]
Is there any possibility that the author name is leftover from a previous install of Co-Authors Plus? No, that doesn't make sense because the Co-Authors Plus plugin is disabled on their site.

There is no custom byline set on this post. Unsetting a custom author in the GUI unsets the custom byline.

The single hero layout uses [HomepageSingle.php](https://github.com/INN/Largo/blob/master/homepages/layouts/HomepageSingle.php). The template used is [full-width-image.php](https://github.com/INN/Largo/blob/master/homepages/templates/full-width-image.php), which creates the post by echoing `$bigStory`. `$bigStory`'s content is set back in `HomepageSingle.php`, where the *function* `bigstory()` returns homepage_big_story_headline(); This is not in a Loop.

Independently of `$bigStory`, the homepage template grabs `$bigStoryPost = largo_home_single_top();` and uses that for the featured image or YouTube video. `$bigStoryPost` is used later.

`homepage_big_story_headline()` is defined at [line 25 of homepages/zones/zones.php](https://github.com/INN/Largo/blob/master/homepages/zones/zones.php#L25). It also sets `$bigStoryPost = largo_home_single_top();`. This is the actual byline code:

    <h5 class="byline"><?php largo_byline(true, true, $bigStoryPost); ?></h5>

`largo_bylines( $echo = true, $exclude_date = false, $post = null )` is declared on [line 86 of inc/post-tags.php](https://github.com/INN/Largo/blob/master/inc/post-tags.php#L86). Since `$bigStoryPost` is an object, `largo_byline` gets the post ID from that. If the `$post` wasn't passed, the function would try `get_the_ID()`, which would *not* work in this circumstance because this is outside any Loop. I think?

Nope! This appears to be within the homepage Loop, which means that `get_the_ID()` returns what appears to be the ID of the sticky post. Even when sticky post is disabled. Wat?

Okay, so maybe that's the problem. Back to figuring out how the byline is generated.

Since Co Authors Plus isn't installed, we can skip that chunk of `largo_byline`. The byline text and links are generated with:

    $authors = largo_author_link( false );

` largo_author_link( $echo = true, $post=null )` is declared on [line 64 of post-tags.php](https://github.com/INN/Largo/blob/master/inc/post-tags.php#L54). If the post isn't passed, the author information is determined by the post in the Loop.

I can't duplicate it in vagrant, though. Changing the author and custom byline on the sticky post doesn't actually change the homepage post.

#418 should fix this, if that is the source of the problem.

**Comment by benlk** [comment]
#418 is merged, and the byline displayed for the top story on http://investigatemidwest.org/ matches the byline on the post: http://investigatemidwest.org/2015/02/06/with-herbicide-resistant-crops-farms-balance-immediate-rewards-with-future-risks/

It is called with a post ID in all the other places it's called, so I'm going to close this.

**Comment by benlk** [comment]
Note to the future: Coauthors' `coauthors_posts_links` cannot take the post ID as an argument, which is why `largo_byline` called outside the Loop with a post ID as an argument and a post with a coauthor will return the wrong byline. This is fixed in Largo 0.5.4 with the longer method of getting coauthors, but it's not (currently) fixed in many child theme re-implementations of `largo_byline` that use older code.
