### ISSUE TITLE
audit/optimize for page load time

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#441]
Let's just start making a list of things we can do to make the site load faster. Then we'll break them out as discrete issues.

**Comment by rnagle** [comment]
Ideas:

- Do some query profiling to see where we're making an excessive number of requests to the database, modify or cut queries where possible.
- Use Chrome or Firefox inspector, network and page performance audit tools to find areas where we can further compartmentalize the CSS and JS in the theme so that only the absolute requirements are loaded on a given request.

**Comment by rnagle** [comment]
Some related tickets, where fixes included some performance benefits and/or optimization.

- #671 class Largo_Related is a query monster and needs to use fewer resources
- #371 slideshow: issues with more than one slideshow per page

**Comment by rnagle** [comment]
Broke this down into slightly smaller tasks and punted to the next milestone. See #688 and #689
