### ISSUE TITLE
ad units on article pages

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#464]
for the one column article page template we need to figure out how to handle some standard ad units and explain how best to set that up so we can head off the inevitable questions and have a plan in place.

**Comment by willhaynes** [comment]
Seattle Times did something similar to this recently. Mike Monteiro wrote about how they approached the problem here:

https://medium.com/@monteiro/all-the-news-where-it-needs-to-fit-e2aefe556f8b

There's a second benefit — these kind of "floating" units with a lot of white space surrounding them tend to perform better than units in a dedicated sidebar. We should also be possible to insert & load them with JS making sure they don't clash with images using the DoubleClick plugin, since ad units are loaded after page load.
