### ISSUE TITLE
ShareThis Tracking

### ISSUE THREAD

**Issue by JoeyColeman** [INN/Largo#699]
ShareThis is useful for most sites and I'm definitely not proposing its removal from the theme package.
Could you assist with which files load ShareThis, I'm going to remove it from my install. I'm running my site HTTPS and a few patrons have complained about the ad-tracking on the site. 

Thanks,

Joey Coleman

**Comment by aschweigert** [comment]
Hi Joey - Not sure which version of Largo you're using but we did ultimately decide to remove ShareThis entirely in a recent release (I believe it was 0.4.1). Our rationale for the change included some of the privacy concerns but also the fact that share buttons don't really get all that much use anyway but particularly share buttons other than fb/twitter/email just seem superfluous. Anyway, updating to the latest version of Largo should include this change so that would probably be the best way to go.

**Comment by JoeyColeman** [comment]
Thanks. I'm using 0.4 and will upgrade to 0.4.1 right away.

**Comment by JoeyColeman** [comment]
Upgrade complete. The speed improvements are very noticeable.
