### ISSUE TITLE
recommended posts widget styling is broken

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#722]
see: http://jira.inn.org/browse/IW-19

even though that widget is deprecated, until we actually remove it it should at least have some basic styling (particularly considering it's in the default stack of widgets added to new sites when largo is installed)

**Comment by benlk** [comment]
If it's in the default stack of widgets added and it's deprecated, should we remove it from the default widgets?

**Comment by willhaynes** [comment]
A step further: Any reason not to remove this widget entirely and replace any instance with a Recent Posts widget configured to replace it?

**Comment by aschweigert** [comment]
that would be fine, let's also make sure to nuke the associated prominence taxonomy terms in the process (assuming we nuke this and the footer featured one)

**Comment by willhaynes** [comment]
I would remove the associate prominence terms by default, but keep them if there are already associated posts with them.

I'd do this out of concern for breaking some users workflow. If they're happy using the `sidebar_featured` and `footer_featured` terms to assign things to those spaces we can just drop a recent posts widget in there configured for that taxonomy and those terms. 

They're happy because nothing changes. We're happy because we don't have to deal with that widget anymore.

**Comment by aschweigert** [comment]
makes sense, should definitely not create it though for new installs

**Comment by willhaynes** [comment]
Doing the simple part first and removing the widget from defaults in #762.

**Comment by benlk** [comment]
Why in the world is the featured image thumbnail put *after* the `h5` in the code? This makes little sense.

**Comment by benlk** [comment]
If #800 is merged, this can be closed.
