### ISSUE TITLE
default set of widgets for "article bottom" widget area

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#728]
In < 0.4 the type and arrangement of items appearing at the bottom of story pages was pre-determined. In 0.4+ we added the article bottom widget area to make this more configurable but when the theme is activated (or updated) this widget area is empty by default. Instead...

For clean installs: we should set the defaults to what we think should typically appear here.

For sites updating from < 0.4: we should probably respect the previous theme options, show the widgets that were "active" on these sites (even though they weren't proper widgets at the time) and the make it clear to sites updating that this is one of the things they'll want to review because there are new options available.

**Comment by aschweigert** [comment]
probably just largo author bio and largo related posts for new installs

**Comment by dryanmedia** [comment]
I'm confused.

It appears something is being set on article-bottom here?
https://github.com/INN/Largo/blob/master/inc/update.php#L173-L183

Based on checks above, and if showing the author box is checked...
https://github.com/INN/Largo/blob/master/inc/update.php#L155-L159

But can't say this update script makes a terrible amount of sense to me.

**Comment by rnagle** [comment]
@dryanmedia The code snippets you point to in your comment appear to do exactly what @aschweigert says should happen for sites upgrading from pre-0.4. It might be worth testing this, since we have had trouble with migrating widgets in the past.

I have a feeling this function might not work properly for some of our sites since we have `largo` and a `lago-dev` themes installed side-by-side. This folder name is what the options framework uses to get and set options, so switching to the newer version of Largo essentially cuts a site off from all of its previous settings.

Anyway, I think you can still set up the Article Bottom widget area as @aschweigert describes. Once that's in place, you should develop a method for testing the upgrade from 0.3 to 0.4+ and verify that the migration function works as expected.

**Comment by aschweigert** [comment]
Yeah, I think the update script is definitely broken, but also there should be a default condition for new installs even if they're not updating (which I think the update message will popup anyway since they don't yet have a version number set).

**Comment by benlk** [comment]
This is probably due to a bug in `largo_instantiate_widget`, where it was checking the wrong `get_option(` for the existing widgets. There's a fix for that in #895.
