### ISSUE TITLE
Load More Stories (Posts) button doesn't appear on Series Landing Page

### ISSUE THREAD

**Issue by meredithinn** [INN/Largo#745]
Mike at the Current reported that the Load More Stories button does not appear on his series landing page http://current.org/series/spectrum-auction/

Help Desk Ticket #242

**Comment by willhaynes** [comment]
Just gave this once over. I think its likely there's some erroneous logic.

This button is loaded with a call to [largo_content_nav('nav-below')](https://github.com/INN/Largo/blob/master/series-landing.php#L138). This function checks to conditions:

1. [If the passed argument is == 'single-post-nav-below'](https://github.com/INN/Largo/blob/3e0c413f3b240a24a59bf4ecc4c93dd6ceb32606/inc/post-tags.php#L494) (its not)
2. [if $wp_query->max_num_pages > 1](https://github.com/INN/Largo/blob/3e0c413f3b240a24a59bf4ecc4c93dd6ceb32606/inc/post-tags.php#L535), which [is defined as](https://codex.wordpress.org/Class_Reference/WP_Query) _"The total number of pages. Is the result of $found_posts / $posts_per_page"_.

If neither of these are true, the function returns without printing DOM for the button.

I think for some reason the second condition which usually evaluates to true is evaluating to false in this case. Maybe because we're not explicit enough when [we build the $wp_query](https://github.com/INN/Largo/blob/master/series-landing.php#L98-L105) in the first place. (what does $found_posts default to?)

**Comment by rnagle** [comment]
Fixed with merge of #786.
