### ISSUE TITLE
Custom Homepage: Sidebars Not Displaying

### ISSUE THREAD

**Issue by vtnq** [INN/Largo#752]
When building a custom homepage, what file controls display of sidebars? The sidebars appear in admin and there is space reserved on the front-end, but the sidebars (except the footer) do not display. A check of the Page Source doesn't show sidebars are included.

Sidebars do appear when I choose the default top-stories homepage. What is weird is that the custom homepage uses the top-stories layout, template and css.

**Comment by aschweigert** [comment]
It's hard to say without having a little more context, but what I think is probably going on is that you need to register any additional widget areas you would want to use in your custom layout. See, for example: https://github.com/INN/Largo/blob/master/homepages/layouts/TopStories.php#L16 where an array of available sidebars are registered so that they would be available to the custom template you build. This structure would be mimicked in the child theme if you were registering a custom layout there.

**Comment by aschweigert** [comment]
Also, for questions like this that are specific to your site (and not Largo core development), it would be better to submit them through our help desk (http://jira.inn.org/servicedesk/customer/portal/4) so we can get back to you more quickly.
