### ISSUE TITLE
in sticky nav, weird padding around site logo

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#767]
![unnamed](https://cloud.githubusercontent.com/assets/490703/8455894/e26a4208-1fd5-11e5-83e5-5d2c8975a113.png)

- [ ] logo should take up the full height of the sticky navbar
- [ ] it should not have the same background hover state as the other nav items (maybe just fade the logo slightly or something instead of changing the background color on hover)

**Comment by aschweigert** [comment]
also, review existing sites using 0.4+ to make sure whatever fix we go with here doesn't break any weird custom stuff they've done to work around the same problem

**Comment by dryanmedia** [comment]
Took a look at this this morning. 

There is this condition for the regular nav:
https://github.com/INN/Largo/blob/master/less/inc/navbar.less#L104-L132

But sticky has separate styles that interfere so I'm working on a patch.

**Comment by benlk** [comment]
We talked about this a bunch back on November 2 and November 3: https://innorg.slack.com/archives/largo-dev/p1446502791000000

The consensus was:

- Don't ask people to put clear space around the logo image
- Do leave the CSS padding on the logo
- No background color on hover on the image or its `a` link.
- On hover, the image gets 75% opacity.

I'm going to close #902, because it removes the padding, and create a new pull request with these changes and file against develop.
