### ISSUE TITLE
show a play icon overlayed on video thumbs on homepage

### ISSUE THREAD

**Issue by aschweigert** [INN/Largo#836]
when a post has a featured video and we're using the thumbnail (on the homepage, etc.) do something to indicate the post has video (same for embedded media, slideshows, etc.)

**Comment by benlk** [comment]
When we save the featured media, [`largo_featured_media_save`](https://github.com/INN/Largo/blob/master/inc/featured-media.php#L527) ensures that if the video's thumbnail is guessed, it will be saved, and then used as a plain attachment. The post's video is saved in the post meta `featured_media`, and `largo_hero_class` can be used to determine if the post is using a featured video.

so:

1. Use largo_hero_class *everywhere* we use get_the_thumbnail
2. Add a style for these thumbnails that overlays the "play" graphic

Otherwise, we're left with this seemingly-bad idea.:

1. During [`largo_media_sideload_image`](https://github.com/INN/Largo/blob/e0a57ca3c050be68a5fef91455029383ef9f3a60/inc/images.php#L72), actually edit the saved image.

**Comment by benlk** [comment]
List of files that need updating:

- [ ] feed-mailchimp.php
- [ ] homepages/templates/full-width-image.php
- [ ] inc/post-tags.php
- [ ] inc/widgets/largo-explore-related.php
- [ ] inc/widgets/largo-recent-posts.php
- [ ] inc/widgets/largo-related-posts.php
- [ ] partials/archive-category-primary-feature.php
- [ ] partials/archive-category-secondary-feature.php
- [ ] partials/author-bio-description.php
- [ ] partials/content-tiny.php
- [ ] partials/content.php
- [ ] partials/hero-featured-image.php

**Comment by benlk** [comment]
https://github.com/INN/Largo/issues/922 is related but not a dependency.

**Comment by benlk** [comment]
Question: Is there any place we do not want a play icon atop the image? Or does this apply only to the homepage?

**Comment by benlk** [comment]
Things that don't work:

- Setting the `img` to half opacity and setting a play icon as the `background-image`: the whole element including the background-image becomes transparent.
- Setting the `img` to half opacity and setting the play icon as the `background-image` of a pseudo-element `img::before` or `img::after: CSS2.1 and CSS3 don't define how pseudo-elements should work with solid, no-child elements like `img` or `object`, so practically all browsers don't render the pseudo-elements.
- Selecting the parent element of `.is-video img`, being the element above the img, and setting its background: There isn't a :parent selector, and might bot be until CSS4
- Selecting `.is-video *:has-child(img)` or similar: possible through jQuery. :sad:

Yet to try:

- The less-restrictive `.is-video > *` with the `background-image` and `.is-video img` for transparency: about to try this.

**Comment by benlk** [comment]
If we end up not taking this route, #921 will need to be addressed separately.

**Comment by benlk** [comment]
#923 merged, so I'm going to close this issues and #921.
