### ISSUE TITLE
2-column classic template should display featured image by default, and filter out duplicate images

### ISSUE THREAD

**Issue by benlk** [INN/Largo#934]
From [HELPDESK-428](http://jira.inn.org/browse/HELPDESK-428):

> discuss whether we might just want to show featured images here by default and filter out dupes as we have with some sites.

Right now, [partials/content-single-classic.php](https://github.com/INN/Largo/blob/master/partials/content-single-classic.php) does not display the featured image, and we might want it to do so.

Duplicate filtering can be done with [largo_remove_hero](https://github.com/INN/Largo/blob/master/inc/post-templates.php#L113) by removing the check for [the single template](https://github.com/INN/Largo/blob/master/inc/post-templates.php#L131)

-----

This would be a good time to grab #590 as well.

**Comment by aschweigert** [comment]
I feel like the behavior should be the same for the single column and two column layouts. It's almost certainly confusing for users to have it behave differently. And since we have the "add featured media" button there no matter what, it would seem to me that the expectation would be to show the featured image by default (on both layouts)
